-- View with the TOP 5 of products with more IN to warehouse

CREATE OR REPLACE VIEW kardex_mayores_entradas AS
SELECT K.COD_PRODUCTO,
P.NOMBRE AS PRODUCTO, 
COUNT(K.COD_PRODUCTO) AS INGRESOS,
SUM(K.CANTIDAD_PRODUCTO) AS TOTAL
FROM KARDEX K
INNER JOIN PRODUCTOS P ON K.COD_PRODUCTO = P.COD_PRODUCTO
WHERE TIPO_TRANSACCION = 'IN' AND ROWNUM <= 5 
GROUP BY K.COD_PRODUCTO, P.NOMBRE
ORDER BY INGRESOS DESC

--Calling view:
--SELECT * FROM kardex_mayores_entradas
